//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swegrant.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swegrant.Server.Properties.Recources", typeof(Recources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///00:05:20,285 --&gt; 00:05:22,514
        ///Vill du inte äta mat?
        ///(in Swedish)
        ///
        ///2
        ///00:05:32,445 --&gt; 00:05:36,210
        ///Vi har en..ett halv äpple här.
        ///
        ///3
        ///00:05:38,125 --&gt; 00:05:39,222
        ///Vill du ha det?
        ///
        ///4
        ///00:05:48,000 --&gt; 00:05:50,137
        ///Would you like to practice some Swedish?
        ///
        ///5
        ///00:05:50,160 --&gt; 00:05:51,160
        ///No.
        ///
        ///6
        ///00:06:15,714 --&gt; 00:06:16,937
        ///Mahyar,
        ///
        ///7
        ///00:06:19,910 --&gt; 00:06:24,710
        ///I read an article about Facebook today,
        ///it was very interesting.
        ///
        ///8
        ///00:06:24,960 --&gt; 00:06:31,970
        ///It was about how  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Theater_01_EN {
            get {
                return ResourceManager.GetString("Theater_01_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///00:05:48,050 --&gt; 00:05:50,020
        ///یه کم میای با هم سوئدئ تمرین کنیم؟
        ///
        ///2
        ///00:05:50,130 --&gt; 00:05:51,403
        ///نه
        ///
        ///3
        ///00:06:15,520 --&gt; 00:06:16,620
        ///!مهیار
        ///
        ///4
        ///00:06:18,400 --&gt; 00:06:18,930
        ///هوم
        ///
        ///5
        ///00:06:19,990 --&gt; 00:06:24,730
        ///امروز داشتم یه مقاله میخوندم در مورد فیسبوک، خیلی بحث اش جالب بود
        ///
        ///6
        ///00:06:24,980 --&gt; 00:06:28,480
        ///راجع به این بود که فضای مجازی و شبکه های اجتماعی
        ///
        ///7
        ///00:06:28,510 --&gt; 00:06:32,120
        ///چقدر به مهارت های زندگی آدما کمک می کنه و
        ///
        ///8
        ///00:06:32,170 --&gt; 00:06:36,190
        ///اصلا کلا چقدر [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Theater_01_FA {
            get {
                return ResourceManager.GetString("Theater_01_FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///00:05:48,050 --&gt; 00:05:50,020
        ///Kan vi öva lite svenska?
        ///
        ///2
        ///00:05:50,130 --&gt; 00:05:51,403
        ///Nej!
        ///
        ///3
        ///00:06:15,520 --&gt; 00:06:16,620
        ///Mahyar!
        ///
        ///4
        ///00:06:18,400 --&gt; 00:06:18,930
        ///Hmmm
        ///
        ///5
        ///00:06:19,990 --&gt; 00:06:24,730
        ///idag läste jag en intressant
        ///artikel om facebook.
        ///
        ///6
        ///00:06:24,980 --&gt; 00:06:28,480
        ///Den handlade om människors
        ///beteenden I sociala
        ///
        ///7
        ///00:06:28,510 --&gt; 00:06:32,120
        ///medier och hur det kan
        ///bidra till deras vardag.
        ///
        ///8
        ///00:06:32,170 --&gt; 00:06:36,190
        ///Hur nära är egentligen cyber [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Theater_01_SV {
            get {
                return ResourceManager.GetString("Theater_01_SV", resourceCulture);
            }
        }
    }
}
